server:
  websocket: ws://111.230.92.145:8000/xiaozhi/v1/
  vision_explain: http://111.230.92.145:8003/mcp/vision/explain
ASR:
  AliyunBLStreamASR:
    api_key: 在此填入你的密钥
    semantic_punctuation_enabled: false
    max_sentence_silence: 900
    multi_threshold_mode_enabled: true
caption_mode: true
enable_websocket_ping: true
close_connection_no_voice_time: 3600
log:
  log_level: INFO
